apiVersion: batch/v1
kind: Job
metadata:
  name: hist-torch-job-%SVS%
spec:
  template:
    metadata:
      name: my-gpu-pod-torch
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gse-key
      containers:
      - name: my-gpu-container-torch
        image: pyushkevich/tangle-cnn-prod:latest
        command: ["/bin/bash"]
        args: ["process_slide_full.sh", "cfn-cluster-test", "gs://svsbucket/%SVSFILE%", "gs://svsbucket/%SVS%_tangle_density.nii.gz", "gs://svsbucket/model_wildcat_upsample/"]
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
      restartPolicy: Never
